/**
 * Publish the host half into `lib/`, and keep the client entry loadable.
 *
 * The node half of this plugin is plain ESM JavaScript with JSDoc types —
 * readable and diffable against the science layer it came from — so there is
 * nothing to compile. It is published by *copying* `src/host` to `lib`, which
 * keeps every relative import identical between the source tree and the
 * installed package, and keeps the "no build step for the host" promise the
 * original layer made.
 *
 * The browser half (milestone 2) builds through `tsdown` into `lib/client.js`.
 * Until that file exists, this script writes a placeholder that speaks the
 * dsh module-loader protocol. It exists because the client module system fails
 * composition — a page-level "failed to load plugins" error — when a package
 * declares `dsh.client` but its bundle is missing, and packages are registered
 * in a profile long before their UI lands. The placeholder registers nothing,
 * so it cannot collide with the real bundle: `tsdown` overwrites it.
 */
import { cp, mkdir, rm, stat, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const pkgRoot = join(here, '..')
const source = join(pkgRoot, 'src', 'host')
const target = join(pkgRoot, 'lib')
const clientEntry = join(pkgRoot, 'src', 'client', 'index.tsx')
const clientBundle = join(target, 'client.js')

const packageName = 'dsh-science-skill'

/**
 * Fail loudly instead of publishing an empty package.
 * @param path - absolute path that must exist.
 * @param what - human-readable description used in the error.
 */
async function require(path, what) {
  try {
    await stat(path)
  } catch {
    throw new Error(`build: ${what} not found at ${path}`)
  }
}

/**
 * @param path - absolute path to test.
 * @returns whether it exists.
 */
async function exists(path) {
  try {
    await stat(path)
    return true
  } catch {
    return false
  }
}

/**
 * The smallest bundle the module loader accepts: a registration whose exports
 * are a package with nothing to contribute. No imports, so nothing can fail to
 * resolve at boot.
 * @returns placeholder bundle source.
 */
function placeholderClient() {
  return `// Generated by scripts/build-host.mjs — replaced by the client build (milestone 2).
window.__ModuleLoader__.load({
  id: ${JSON.stringify(packageName)},
  factory: () => ({ name: ${JSON.stringify(packageName)}, inject: [], apply: () => {} })
});
`
}

async function main() {
  await require(join(source, 'index.js'), 'host entry')
  await require(join(source, 'schema', 'catalog.schema.json'), 'bundled catalog schema')
  await rm(target, { recursive: true, force: true })
  await mkdir(target, { recursive: true })
  await cp(source, target, { recursive: true })
  console.log('build: host half copied to lib/')

  if (await exists(clientEntry)) {
    console.log('build: client sources present — run tsdown to produce lib/client.js')
  } else {
    await writeFile(clientBundle, placeholderClient(), 'utf8')
    console.log('build: placeholder lib/client.js written (the client half is not built yet)')
  }
}

await main()
