/**
 * ScienceCategoryIcon: one line-style SVG glyph per category icon name.
 *
 * The sidebar tree and the category settings picker draw the same glyphs, so the
 * rail reads as a coherent family: 24×24, one stroke geometry (2px grid, rounded
 * caps), and `currentColor` for ink so the academic hover/active states apply
 * without any per-icon color. Path data is inlined from the science layer's
 * single source of truth (regenerated by
 * `science/workbench-web/sync-category-icons.mjs`); artwork is Lucide,
 * ISC licensed.
 */
import type { JSX } from 'react'
import { CATEGORY_ICON_PATHS, DEFAULT_CATEGORY_ICON } from './icon-paths.ts'

/**
 * Legacy category keys → icon names. The categories API reports an icon name,
 * so this only serves callers that still hand in a raw category key.
 */
const LEGACY_CATEGORY_ICONS: Readonly<Record<string, string>> = {
  literature: 'book-open',
  writing: 'pen-line',
  'data-analysis': 'chart-column',
  figure: 'chart-line',
  review: 'star',
  presentation: 'monitor',
  lab: 'flask-conical',
  topic: 'lightbulb',
  outcome: 'medal',
  document: 'file-text',
  misc: 'package',
}

/** Props for one category glyph. */
export interface ScienceCategoryIconProps {
  /** Icon name (`book-open`) or, for older callers, a category key. */
  name: string
  /** Extra class from the consuming CSS module. */
  className?: string | undefined
  /** Rendered edge length in px; defaults to the sidebar's 16. */
  size?: number
}

/** Render one category glyph; an unknown name falls back to the folder. */
export function ScienceCategoryIcon({ name, className, size = 16 }: ScienceCategoryIconProps): JSX.Element {
  const resolved = LEGACY_CATEGORY_ICONS[name] ?? name
  const markup = CATEGORY_ICON_PATHS[resolved] ?? CATEGORY_ICON_PATHS[DEFAULT_CATEGORY_ICON] ?? ''
  return (
    <svg
      className={className}
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      aria-hidden="true"
      stroke="currentColor"
      strokeWidth={1.8}
      strokeLinecap="round"
      strokeLinejoin="round"
      // Local, generated path data (never remote or user input).
      dangerouslySetInnerHTML={{ __html: markup }}
    />
  )
}
